//VERTICLE LIST
export const orderItems = [
  {
    AWBStatus: 'MANIFESTED',
    OderDate: '01-02-2033',
    WaybillNo: '51561551',
    clientCode: '***',
    ClientName: 'Test1',
    ReferenceId: '11111',
    Courier: 'trackon',
    PaymentType: 'cash',
    ConsigneeName: 'Test1',
    Destination: 'chandigarh ,chandigarh',
    Pieces: '1',
    Weight: '10g',
    Mode: 'airplane',
  },
  {
    AWBStatus: 'IN TRANSIT',
    OderDate: '02-03-2023',
    WaybillNo: '51561551',
    clientCode: '***',
    ClientName: 'Test2',
    ReferenceId: '11111',
    Courier: 'trackon',
    PaymentType: 'cash',
    ConsigneeName: 'Test2',
    Destination: 'chandigarh ,chandigarh',
    Pieces: '1',
    Weight: '10g',
    Mode: 'airplane',
  },
  {
    AWBStatus: 'DELIVERED',
    OderDate: '04-01-2023',
    WaybillNo: '51561551',
    clientCode: '***',
    ClientName: 'Test3',
    ReferenceId: '11111',
    Courier: 'trackon',
    PaymentType: 'cash',
    ConsigneeName: 'Test3',
    Destination: 'chandigarh ,chandigarh',
    Pieces: '1',
    Weight: '10g',
    Mode: 'airplane',
  },
  {
    AWBStatus: 'RETURNED',
    OderDate: '06-03-2001',
    WaybillNo: '51561551',
    clientCode: '***',
    ClientName: 'Test4',
    ReferenceId: '11111',
    Courier: 'trackon',
    PaymentType: 'cash',
    ConsigneeName: 'Test4',
    Destination: 'chandigarh ,chandigarh',
    Pieces: '1',
    Weight: '10g',
    Mode: 'airplane',
  },
];
